.core-defs:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    JNI_PATH: libretro
    CORENAME: dosbox_svn

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - project: 'libretro-infrastructure/ci-templates'
    file: '/libnx-static.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/vita-static.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

stages:
  - build-prepare
  - build-shared
  - build-static
  - test

#Desktop
libretro-build-linux-x64:
  extends:
    - .core-defs
    - .libretro-linux-x64-make-default
  variables:
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile.libretro
    platform: unix
    BUNDLED_SDL: 1
  cache:
    key: "$CI_COMMIT_REF_SLUG-linux-x64-1"
    untracked: false
    paths:
      - libretro/deps_bin/
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}
    - strip ${MAKEFILE_PATH}/${CORENAME}_libretro.so

libretro-build-windows-x64:
  extends:
    - .core-defs
    - .libretro-windows-x64-mingw-make-default
  variables:
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile.libretro
    CC: gcc
    CXX: g++
    platform: win
    TARGET_TRIPLET: x86_64-w64-mingw32.static
    BUNDLED_SDL: 0
  image: $CI_SERVER_HOST:5050/libretro-infrastructure/libretro-build-mxe:latest
  cache:
    key: "$CI_COMMIT_REF_SLUG-windows-x64-1"
    untracked: false
    paths:
      - libretro/deps_bin/
  script:
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} deps
    - make -C ${MAKEFILE_PATH} -f ${MAKEFILE} -j${NUMPROC}
    - ${TARGET_TRIPLET}-strip ${MAKEFILE_PATH}/${CORENAME}_libretro.dll

# Android
android-armeabi-v7a:
  extends:
    - .core-defs
    - .libretro-android-jni-armeabi-v7a
  cache:
    key: "$CI_COMMIT_REF_SLUG-android-armeabi-v7a-1"
    untracked: false
    paths:
      - libretro/deps_bin/

android-arm64-v8a:
  extends:
    - .core-defs
    - .libretro-android-jni-arm64-v8a
  cache:
    key: "$CI_COMMIT_REF_SLUG-android-arm64-v8a-1"
    untracked: false
    paths:
      - libretro/deps_bin/

android-x86_64:
  extends:
    - .core-defs
    - .libretro-android-jni-x86_64
  cache:
    key: "$CI_COMMIT_REF_SLUG-android-x86_64-1"
    untracked: false
    paths:
      - libretro/deps_bin/

android-x86:
  extends:
    - .core-defs
    - .libretro-android-jni-x86
  cache:
    key: "$CI_COMMIT_REF_SLUG-android-x86-1"
    untracked: false
    paths:
      - libretro/deps_bin/

# Static
libretro-build-libnx-aarch64:
  extends:
    - .core-defs
    - .libretro-libnx-static-retroarch-master
  variables:
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile.libretro
    BUNDLED_SDL: 0
  cache:
    key: "$CI_COMMIT_REF_SLUG-libnx-aarch64-1"
    untracked: false
    paths:
      - libretro/deps_bin/

libretro-build-vita:
  extends:
    - .core-defs
    - .libretro-vita-static-retroarch-master
  variables:
    MAKEFILE_PATH: libretro
    MAKEFILE: Makefile.libretro
    BUNDLED_SDL: 0
  cache:
    key: "$CI_COMMIT_REF_SLUG-vita-1"
    untracked: false
    paths:
      - libretro/deps_bin/
